### ISSUE TITLE
React on every message in a Discord chat

### ISSUE THREAD

**Issue by Nesonica** [Zero6992/chatGPT-discord-bot#118]
Hi @Zero6992 ,

thank you for this gorgeous repository, it helps my Discord community a lot and works perfectly!
I am using Restream Chat to have my YouTube, Twitch and Discord viewers of my livestreams interact with each other. Unfortunately they can not just write something like "/chat what is the evolution of the Pokémon bulbasaur?" because the output on my Discord channel would be like:

Restream Bot: [YouTube: Zero6992] /chat what is the evolution of the Pokémon bulbasaur?

Is there a way to have the ChatGPT react on every message that comes up in a specific Discord Chat?
And is there a way to have the ChatGPT answer always with a specific tag/subject (here: "pokemon")?

Thank you very much for your help and keep up the good works!
Best regards
Nes

**Comment by Zero6992** [comment]
Responding to every message sent by default would cause the bot to process a large amount of irrelevant and unrelated messages, so I believe using slash commands would be a better approach to do this

**Comment by Zero6992** [comment]
The second problem is that we're currently using GPT-3 model instead of ChatGPT's GPT-3.5, GPT-3 does not have the ability to carry over context

Btw, OpenAI has announced that the official API for GPT-3.5 will be released soon, I believe that will allow you to direct the conversation more effectively by specifying the topic you want to discuss next
